# Generated by Django 3.2 on 2021-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bus', models.IntegerField(verbose_name='ID автобуса')),
                ('board_number', models.CharField(max_length=50, verbose_name='Бортовый номер')),
                ('regist_number', models.CharField(max_length=9, verbose_name='Регистрационный номер')),
                ('number_of_places', models.IntegerField(verbose_name='Число мест')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
            ],
        ),
    ]
