# Generated by Django 3.2 on 2021-04-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210412_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='regist_number',
            field=models.CharField(max_length=9, verbose_name='Регистрационный номер'),
        ),
    ]
