# Generated by Django 3.2 on 2021-04-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bus_regist_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_num',
            field=models.CharField(max_length=20, verbose_name='Номер рейса'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_number',
            field=models.CharField(max_length=9, verbose_name='Номер маршрута'),
        ),
    ]
