# Generated by Django 3.2 on 2021-04-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210412_1620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
