# Generated by Django 3.2 on 2021-04-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_flight_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='stop_to_address',
            field=models.CharField(max_length=50, verbose_name='Пункт назначения'),
        ),
    ]
